### ISSUE TITLE
saTemper

### ISSUE THREAD

**Issue by ajrominger** [santafemha/parTempeR#1] opened 2019-05-22 22:55 UTC
there's an exported and documented function called `saTemper` that does not have a counterpart in ./R.  Does this function need to be written, or does reference to it need to be removed?  Currently the package does not build.

**Comment by MichaelHoltonPrice** [comment] 2019-05-23 17:42
This was caused by an error in renaming from saTemper.R / saTemperBest.R to parTemper.R / parTemperBest.R. It is now fixed.

**Closed as completed by MichaelHoltonPrice** 2019-05-23 17:42 UTC
